language: cpp
compiler: clang

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install -y  libtag1-dev libsndfile1-dev libportaudio-dev cmake

script: cmake .; make
