language: cpp


matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.6
    - os: osx
      osx_image: xcode7.3
      sudo: required
      compiler: clang

install: ./.travis-dependencies.sh
  

script:
  - cmake .
  - make
