language: cpp
compiler: clang

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

before_install:
  - wget https://github.com/Viq111/travis-container-packets/releases/download/cmake-3.1.2/cmake.tar.bz2
  - tar -xjf cmake.tar.bz2
  - rm cmake.tar.bz2
  - export PATH=$(pwd)/cmake/bin:$PATH
  - sudo apt-get update
  - sudo apt-get install -y  libtag1-dev libsndfile1-dev libportaudio-dev clang-3.5 libstdc++ libstdc++-4.8-dev

script:
  - cmake .
  - make
