language: cpp
compiler: clang

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

before_install:
  wget --no-check-certificate https://cmake.org/files/v3.4/cmake-3.4.3.tar.gz
      && tar -xzf cmake-3.4.3.tar.gz
      && sudo cp -fR cmake-3.4.3-Linux-i386/* /usr
  - sudo apt-get update
  - sudo apt-get install -y  libtag1-dev libsndfile1-dev libportaudio-dev

script:
  - cmake .
  - make
