language: cpp


matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
  include:
    - os: osx
      osx_image: xcode7.3
      sudo: required
      compiler: clang

before_install: chmod +x .travis-dependencies.sh

install: ./travis-dependencies.sh
  

script:
  - cmake .
  - make
